# Specific configuration for motor IDs and positions for the relevant nodes

proportional_controller:
  ros__parameters:
    motor_ids: [35, 36, 37]  # Motor IDs used by the proportional controller

euler_integrator_controller:
  ros__parameters:
    motor_ids: [35, 36, 37]  # Motor IDs used by the integrator

close:
  ros__parameters:
    motor_ids: [35, 36, 37]  # Motor IDs used by the close action

open:
  ros__parameters:
    motor_ids: [35, 36, 37]  # Motor IDs used by the open action
    motor_position: [100.0, 100.0, 100.0]  # Specific positions for the motors during opening

hand_driver:
  ros__parameters:
    motor_ids: [31, 32, 33, 34, 35, 36, 37, 38]  # All motor IDs for the hand driver
